### ISSUE TITLE
My first coding problem

### ISSUE THREAD

**Issue by Elisa0122** [Elisa0122/using-markbot#1]
My code isn<t doing what I expect it to do.
In Markbot the name is different than GitHub.

![nicot-elisa-markbot](https://user-images.githubusercontent.com/83783101/119045891-05de1d00-b98a-11eb-9940-73c012650619.png)
![nicot-elisa-github](https://user-images.githubusercontent.com/83783101/119045945-18585680-b98a-11eb-8628-7763b8efe3c6.png)

Thank you for your help @abhaysharma

**Comment by abhaysharma** [comment]
Have you turned on GitHub pages for this repository by going in Settings > Pages and then selecting master as the branch from drop down?

**Comment by Elisa0122** [comment]
there is no master as a branch 
<img width="1455" alt="Screen Shot 2021-05-20 at 7 16 21 PM" src="https://user-images.githubusercontent.com/83783101/119060334-fb2e8280-b99f-11eb-9fd9-e2b118a486f1.png">

why Github think that the name of the URL has to be https://elisa nicot.github.io/using-markbot/ even if we can't use space in the URL?
And in fact in GitHub is https://elisa0122.github.io/using-markbot/
Where could I change the name?

@abhaysharma

**Comment by Elisa0122** [comment]
I fix the problem. I was login with the wrong username on markbot
